language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - "3.6"
before_install:
  - nvm install 8.12.0
install:
  - make requirements-dev yarn-install
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
